{% set name = "grheat" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grheat-{{ version }}.tar.gz
  sha256: 00640a4b41950a44073dcba0a22acbfaecd4e2555be6869d358a4d80dc17270f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - grheat
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/test_absorber.py
    - tests/test_line.py
    - tests/test_plane.py
    - tests/test_point.py
  commands:
    - pytest tests/test_absorber.py
    - pytest tests/test_line.py
    - pytest tests/test_plane.py
    - pytest tests/test_point.py

about:
  home: https://github.com/scottprahl/pygrin
  summary: A python module using Green's functions to solve heat transfer problems.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://grheat.readthedocs.io/
  dev_url: https://github.com/scottprahl/grheat

extra:
  recipe-maintainers:
    - scottprahl
